### ISSUE TITLE
feature block arrangement

### ISSUE THREAD

**Issue by gwijthoff** [joshosbrn/jekyons#18]
Any idea why the front page feature blocks fail to line up in order if you list more than six features in `features.yml`? The blocks arrange themselves with gaps. See for instance: <https://gwijthoff.github.io/jekyons-test/>

This may have something to do with the tachyons clearfix in `index.html` but I'm not sure.

**Comment by hacknug** [comment]
That's because you're using floats to lay things down and the second item on that list is taller than the third (and this is what's supposed to happen with floats). You could set their height explicitly or use flexbox to fix that.

**Comment by gwijthoff** [comment]
Beautiful, thanks friend!
